version: '3'
services:
  jira:
    image: konan/jira
    container_name: jira
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - ./data:/var/atlassian/jira
    networks:
      jira_net:

networks:
  jira_net:
    ipam:
      driver: default
